export const GET_PROBLEMS_BY_CODE = 'GET_PROBLEMS_BY_CODE';
export const GET_PROBLEMS_BY_CATEGORY = 'GET_PROBLEMS_BY_CATEGORY';
export const ADD_PROBLEM = 'ADD_PROBLEM';
export const REMOVE_PROBLEM = 'REMOVE_PROBLEM';
export const UPDATE_CHALLENGE_NAME = 'UPDATE_CHALLENGE_NAME';
export const ADDED_CHALLENGE = 'ADDED_CHALLENHE';
